name: Django ci/cd
on:
        push:
                branches: [main]
jobs:
        test:
                runs-on: ubuntu-latest
                env:
                        PG_NAME: ${{ secrets.PG_NAME }}
                        PG_USER: ${{ secrets.PG_USER }}
                        PG_PASSWORD: ${{ secrets.PG_PASSWORD }}
                        PG_HOST: ${{ secrets.PG_HOST }}
                        PG_PORT: ${{ secrets.PG_PORT }}
                        SECRET_KEY: ${{ secrets.SECRET_KEY }}
                        ALLOWED_HOSTS: ${{ secrets.ALLOWED_HOSTS }}
                services:
                        postgres_main:
                                image: postgres:latest
                                env:
                                        PG_USER: ${{ env.PG_USER }}
                                        PG_PASSWORD: ${{ env.PG_PASSWORD }}
                                        PG_NAME: ${{ env.PG_NAME }}
                                ports:
                                        - 5432:5432
                                options:
                                        --health-cmd pg_isready
                                        --health-interval 5s
                                        --health-timeout 5s
                                        --health-retries 5
                steps:
                        - name: Проверяем репозиторий на наличие изменений
                          uses: actions/checkout@v2
                        - name: Установка python
                          uses: actions/setup-python@v2
                          with:
                                  python-version: 3.8
                        - name: Установка библиотек
                          run: pip install -r requirements.txt
                        - name: Тестинг
                          run: python manage.py test
                          env:
                                  PG_NAME: ${{ secrets.PG_NAME }}
                                  PG_USER: ${{ secrets.PG_USER }}
                                  PG_PASSWORD: ${{ secrets.PG_PASSWORD }}
                                  PG_HOST: ${{ secrets.PG_HOST }}
                                  PG_PORT: ${{ secrets.PG_PORT }}
        deploy:
                runs-on: ubuntu-latest
                needs: test
                steps:
                        - name: deploy
                          uses: appleboy/ssh-action@master
                          with:
                                  host: ${{ secrets.SSH_HOST}}
                                  username: ${{ secrets.SSH_USERNAME }}
                                  key: ${{ secrets.SSH_KEY }}
                                  script: |
                                          cd /home/user/django_CRUD_DRF/stocks_products
                                          git pull origin main
                                          source /env/bin/activate
                                          pip install -r requirements.txt
                                          python manage.py migrate
                                          python manage.py collectstatic --noinput
                                          systemctl restart gunicorn
